kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mern-notes
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30082   # matches nodePort in 04-frontend.yaml
        hostPort: 30082
        protocol: TCP